import { getPolicies, canExportPolicy, POLICY_TITLES } from '@/lib/soc2/policy-generator';
import type { PolicyDocument, PolicyStatus } from '@/lib/soc2/policy-generator';

const STATUS_LABELS: Record<PolicyStatus, string> = {
  draft: 'Draft',
  under_review: 'Under Review',
  approved: 'Approved',
  exported: 'Exported',
};

const STATUS_COLORS: Record<PolicyStatus, string> = {
  draft: '#6b7280',
  under_review: '#d97706',
  approved: '#16a34a',
  exported: '#2563eb',
};

function StatusBadge({ status }: { status: PolicyStatus }) {
  return (
    <span
      style={{
        display: 'inline-block',
        padding: '2px 10px',
        borderRadius: '12px',
        fontSize: '0.78rem',
        fontWeight: 600,
        color: '#fff',
        background: STATUS_COLORS[status],
        letterSpacing: '0.02em',
      }}
    >
      {STATUS_LABELS[status]}
    </span>
  );
}

function PolicyCard({ policy }: { policy: PolicyDocument }) {
  const exportable = canExportPolicy(policy);
  const lowConfidenceSections = policy.current_version.sections.filter(
    (s) => s.confidence_score < 0.75 && !s.reviewed
  );
  const totalSections = policy.current_version.sections.length;
  const reviewedCount = policy.current_version.sections.filter(
    (s) => s.confidence_score >= 0.75 || s.reviewed
  ).length;

  return (
    <div className="card" style={{ marginBottom: '1rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '0.5rem' }}>
        <div>
          <h2 style={{ margin: 0, fontSize: '1.1rem' }}>
            <a href={`/policies/${policy.id}`}>{policy.title}</a>
          </h2>
          <p className="muted" style={{ margin: '0.25rem 0 0' }}>
            Version {policy.current_version.version} &middot; Generated by AI &middot; Updated {new Date(policy.updated_at).toLocaleDateString()}
          </p>
        </div>
        <StatusBadge status={policy.status} />
      </div>

      <div style={{ marginTop: '0.75rem', display: 'flex', gap: '1.5rem', flexWrap: 'wrap', alignItems: 'center' }}>
        <span className="muted" style={{ fontSize: '0.875rem' }}>
          {totalSections} sections &middot; {reviewedCount}/{totalSections} reviewed
        </span>
        {lowConfidenceSections.length > 0 && (
          <span style={{ fontSize: '0.875rem', color: '#d97706', fontWeight: 500 }}>
            {lowConfidenceSections.length} section{lowConfidenceSections.length > 1 ? 's' : ''} need review
          </span>
        )}
        {exportable && policy.status === 'approved' && (
          <span style={{ fontSize: '0.875rem', color: '#16a34a', fontWeight: 500 }}>
            Ready to export
          </span>
        )}
      </div>

      <div style={{ marginTop: '0.875rem' }}>
        <a href={`/policies/${policy.id}`} className="btn secondary" style={{ marginRight: '0.5rem' }}>
          Edit Policy
        </a>
        {!exportable && (
          <span className="muted" style={{ fontSize: '0.8rem' }}>
            Complete all section reviews before exporting
          </span>
        )}
      </div>
    </div>
  );
}

export default async function PoliciesPage() {
  const policies = await getPolicies();

  return (
    <main>
      <h1>SOC 2 Policy Document Suite</h1>
      <p>
        AI-generated security policies covering SOC 2 Trust Service Criteria. Each policy is
        pre-populated with your company variables and requires human review of flagged sections
        before export to the evidence room.
      </p>

      <div style={{ marginBottom: '1.5rem' }}>
        <a href="/policies/information-security" className="btn">
          Generate New Version
        </a>
      </div>

      {policies.length === 0 ? (
        <div className="empty">
          <p>No policies generated yet.</p>
          <p className="muted">
            Click &ldquo;Generate New Version&rdquo; to create your SOC 2 policy suite.
          </p>
        </div>
      ) : (
        <>
          <div style={{ marginBottom: '0.5rem', display: 'flex', gap: '1rem', flexWrap: 'wrap', alignItems: 'center' }}>
            <span className="muted" style={{ fontSize: '0.875rem' }}>
              {policies.length} polic{policies.length === 1 ? 'y' : 'ies'} &mdash;{' '}
              {Object.keys(POLICY_TITLES).length} required for SOC 2 Type II
            </span>
          </div>
          {policies.map((policy) => (
            <PolicyCard key={policy.id} policy={policy} />
          ))}
        </>
      )}
    </main>
  );
}
